### ISSUE TITLE
translation missing: es.refinery.plugins.refinerycms_portfolio.title

### ISSUE THREAD

**Issue by AlejoXML** [refinery/refinerycms-portfolio#111]
I get this error with english version too.
This error appeared after update to Fix plugin url #107 
backend error: ![backendt](http://i.imgur.com/mtUuflo.png)

Thanks for help :smile_cat:

**Comment by tronmcp** [comment]
I received this error as well, I put the translation in the main en.yml file as a work around but had not had a chance to report it yet.

**Comment by bricesanchez** [comment]
This commit 6d6417ba2f46c5c95fbab40683a7ea672fa20b9f should fix your problem. :)

**Comment by mpvoss** [comment]
Thanks for the fix!!! Could not figure out why my project was breaking.  You're the best.

**Comment by AlejoXML** [comment]
Thanks for fix !! :smile:

**Comment by tronmcp** [comment]
Thanks for the fix!

**Comment by bricesanchez** [comment]
Thank you :)
