### ISSUE TITLE
in the readme.md file ...

### ISSUE THREAD

**Issue by Astr0surf3r** [refinery/refinerycms-portfolio#116]
Hi,

the 'refinerycms-portfolio "Refinery CMS 2-1 stable branch"' link in the readme.md file doesn't work ...

bye and goodnight!

A

**Comment by bricesanchez** [comment]
Thanks, it fixed now : https://github.com/refinery/refinerycms-portfolio/commit/971a3ea4036f14fd4f63da32a5570618ab8f2322
