### ISSUE TITLE
"No items yet" translation missing for admin top-level images list

### ISSUE THREAD

**Issue by gwagener** [refinery/refinerycms-portfolio#79]
If no top level images have been added, viewing the list displays "i18n: No Items Yet".  The translations files are missing refinery.admin.items.index.no_items_yet.  Also, I think there are some unused translations lying around in there.  Possibly some file structures changed and the translation paths weren't updated.

**Comment by bricesanchez** [comment]
The issue is outdated, i'm closing it.
